version: "3"

services:
  app:
    build: .
    container_name: iqosiluma.moscow
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=iqosiluma.moscow
      - LETSENCRYPT_HOST=iqosiluma.moscow
      - LETSENCRYPT_EMAIL=qwe@email.com
    networks:
      - web
    volumes:
      # Все сайты используют одну и ту же папку с картинками
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # - /var/www/iqosiluma.moscow/.next:/app/.next

networks:
  web:
    external: true
